variables:
  docker_image_tag: $(Build.BuildId)
  project_name: iu-gtfs-rest
  docker_image_name: iunera/$(project_name)
  System.Debug: false
  target_env: fahrbar-prod

resources:
  repositories:
    - repository: templates
      type: github
      name: iunera/azure-devops-templates

trigger:
  branches:
    exclude:
      - refs/heads/master

stages:
  - template: docker_and_helm/azure-pipelines.yml@templates
    parameters:
      file_type_to_copy: helm
