apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iu-gtfs-rest
  namespace: fahrbar-prod
spec:
  releaseName: iu-gtfs-rest
  targetNamespace: fahrbar-prod
  chart:
    spec:
      chart: springboot
      version: ">=2.0.0"
      sourceRef:
        kind: HelmRepository
        name: iunera-helm-charts
        namespace: helmrepos
  interval: 1m0s
  install:
    createNamespace: false
  values:
    image:
      repository: iunera/iu-gtfs-rest
      tag: docker_image_tag
      pullPolicy: IfNotPresent

    extraArgs:
      - --server.port=8080
      - --spring.application.name=iu-gtfs-rest-prod
      - --spring.datasource.url=${SPRING_DATASOURCE_URL}
      - --spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
      - --spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

    env:
      - name: SPRING_DATASOURCE_URL
        valueFrom:
          secretKeyRef:
            name: gtfs-datasource-postgres
            key: url
      - name: SPRING_DATASOURCE_USERNAME
        valueFrom:
          secretKeyRef:
            name: gtfs-datasource-postgres
            key: username
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: gtfs-datasource-postgres
            key: password

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: role
                  operator: In
                  values:
                    - service-node

    resources:
      limits:
        cpu: null
        memory: 1Gi
        ephemeral-storage: "4Gi"
      requests:
        cpu: null
        memory: 512Mi
        ephemeral-storage: "2Gi"
